### PR TITLE
Kyle improvement

### LINKED ISSUE #35: Fix sizes of info boxes
Right now, it looks like the boxes on the home page, with the information, are of different sizes - which may be due to dynamic sizing. It would look better if they were of the same size:
design

### PR DESCRIPTION
**Pull request by Kyle199910**
Did some changes based off the website feedback from PPC2, such as adding questions to FAQ, moving the button and adjusting some text

### CODE REVIEW

**Comment by Rolo123y** [comment]
What are your thoughts on centering the cards under the Begin button? @Kyle199910 @gaurav613 
image

**Review by Rolo123y — COMMENTED** [review]
The following cards on the home page are kind of difficult to read because of the light colors on a white background. Maybe a darker shade of them?
image

**Comment by Kyle199910** [comment]
> What are your thoughts on centering the cards under the Begin button? @Kyle199910 @gaurav613 image

the current positioning of the cards are fine and looks good,

**Comment by Rolo123y** [comment]
> 

then are we closing the issue to align them?

**Comment by Kyle199910** [comment]
ohhh card align, then i think it would be good to line up the top of the cards

**Comment by gaurav613** [comment]
This is just a suggestion: I think the changing of the outline colors when hovering may confuse users as to whether it's clickable or not - which I think was mentioned in previous PPC feedback. Maybe we can remove the hover effect, or by default have those colors in the outline?

**Comment by gaurav613** [comment]
Looks good, merging now.

**Pull request merged**
