### PR TITLE
Inputs enhancements

### PR DESCRIPTION
**Pull request by Rolo123y**
- Added a popup which displays example electricity bills
- Added some validations for each input. for example, if a floatfield is not a positive number, you will see a message under the input on submit
- The selected value in the Monthfield must be greater than (2015, 1, 1) so we do not get old bills
- In the Tiered form, we now have 'Lower' and 'Upper' for the usage table 
- Added a Location selectfield
- General css formatting with these new fields and validations

### CODE REVIEW

**Review by gaurav613 — CHANGES_REQUESTED** [review]
A few things:
- Looks like you've not committed the images for the hydro bills, so they don't appear in the modal after clicking the question mark icon
- For the date entry, it could be useful if a threshold was specified (eg. enter bill after 2015) instead of just asking for a more recent bill
- Could it be possible/viable to add a reset button along with the submit button?
- Is price per KWH needed as an input, or will that be a fixed value for everyone?

**Comment by Rolo123y** [comment]
Is price per KWH needed as an input, or will that be a fixed value for everyone?

- We will try to auto fill this input based on the chosen Date. But if we have the wrong value, they can input it themselves to the correct value on their bill

**Comment by gaurav613** [comment]
Has the autofill been implemented? Don't see it - if not, everything else looks good.

**Comment by Rolo123y** [comment]
> Has the autofill been implemented? Don't see it - if not, everything else looks good.

autofill has not yet been implemented. An issue has been created and its the next step for another branch.

**Review by gaurav613 — APPROVED** [review]
Looks good to me, will merge.

**Pull request merged**
