### PR TITLE
adding payback period and equivalencies. Edited styling of these additions

### LINKED ISSUE #46: Display GHG Equivalency Results and Payback Period for Powerwall

### PR DESCRIPTION
**Pull request by Rolo123y**
- Added Payback period
- Added equivalency: phones_charged_10_years
- Added equivalency: miles_driven
- Some styling of these additions

### CODE REVIEW

**Comment by Rolo123y** [comment]
feel free to request any changes. I'm having trouble thinking of design improvements here!

**Comment by gaurav613** [comment]
Looks good so far, the only suggestion I have is that you can make the boxes housing both the outputs the same - things such as the title(payback period is not bold, when equivalency is), and the box size/height.
equivalencies

**Comment by gaurav613** [comment]
One more suggestion - can you move the text from the box to the tooltip, for the payback period, 
it could be something like: **Considering the cost of a Tesla Powerwall to be $10,000, the time it would take to break even on the investment**
payback

This would make the boxes standardized(when compared to the Equivalencies)

**Comment by Rolo123y** [comment]
> 

done

**Comment by gaurav613** [comment]
A minor change needed - there seems to be no padding towards the left of the payback period text. Everything else looks good.
payback_margin

**Comment by Rolo123y** [comment]
done

**Comment by gaurav613** [comment]
Looks good, merging now.

**Pull request merged**
